#!/usr/bin/env python3
"""Classification-cap enforcement gate (M7).

Exercises `classify_entity()` / `_classification_cap()` / `_filter_by_classification()`
directly, then drives wiki_ask / wiki_pack / wiki_audit / stats / resolve end-to-end
against the SAME synthetic fixture used by test_golden_queries.py
(fixtures/golden_corpus/, generated by fixtures/build_golden_corpus.py) — extended
here with fixtures/golden_corpus/manifest.json declaring a mixed classification_map:

    entities/concept/**                                       -> public
    entities/concept/atlas-marine-named-partner-routing.json   -> confidential  (override)
    entities/person/**                                         -> restricted
    (no pattern matches org/*)                                  -> internal (corpus-level default)

That gives every rank in the public<internal<confidential<restricted enum at
least one entity, plus one longest-match-wins override, over a corpus small
enough to hand-count expected withheld_count per cap.

Fully hermetic: no network calls, no real company-brain data — see
fixtures/README.md for the data-governance rationale (this repo, VictorGjn/
agent-skills, is PUBLIC).

Run: python -m pytest entitystore/scripts/tests/test_classification_gate.py -v
"""
from __future__ import annotations

import asyncio
import json
import os
import pathlib
import sys
import threading
import unittest

SCRIPTS = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

import cb_engine as ce  # noqa: E402

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"
CORPUS = FIXTURES / "golden_corpus"

# Hand-counted from golden_seed.json + the manifest above.
CONCEPT_IDS = {
    "concept:atlas-marine-demand-theme", "concept:atlas-marine-stability-theme",
    "concept:borealis-robotics-named-partner-sensing", "concept:borealis-robotics-demand-theme",
    "concept:borealis-robotics-stability-theme", "concept:meridian-foils-named-partner-integration",
    "concept:meridian-foils-demand-theme", "concept:meridian-foils-stability-theme",
    "concept:foil-stability-cluster",
}  # 9 concepts -> public (10th concept below is the override)
CONFIDENTIAL_OVERRIDE_ID = "concept:atlas-marine-named-partner-routing"  # -> confidential
ORG_IDS = {"org:atlas-marine", "org:borealis-robotics", "org:meridian-foils"}  # -> internal (fallback)
PERSON_IDS = {"person:elena-vasko", "person:tomas-reyk", "person:aiko-ferrant"}  # -> restricted

TOTAL = len(CONCEPT_IDS) + 1 + len(ORG_IDS) + len(PERSON_IDS)
assert TOTAL == 16, TOTAL


def _ensure_corpus_built() -> None:
    if (CORPUS / "entities").exists():
        return
    sys.path.insert(0, str(FIXTURES))
    import build_golden_corpus  # noqa: E402
    build_golden_corpus.build(write=True)


class TestClassifyEntity(unittest.TestCase):
    """Pure-function precedence checks — no corpus I/O."""

    def test_no_manifest_fields_fails_closed_to_restricted(self):
        self.assertEqual(
            ce.classify_entity({"id": "concept:x", "kind": "concept"}, {}), "restricted")

    def test_corpus_level_data_classification_is_the_fallback(self):
        self.assertEqual(
            ce.classify_entity({"id": "concept:x", "kind": "concept"},
                               {"data_classification": "internal"}),
            "internal")

    def test_classification_map_overrides_corpus_level(self):
        manifest = {"data_classification": "internal",
                    "classification_map": {"entities/concept/**": "restricted"}}
        self.assertEqual(
            ce.classify_entity({"id": "concept:x", "kind": "concept"}, manifest),
            "restricted")

    def test_longest_most_specific_glob_wins(self):
        manifest = {"data_classification": "internal",
                    "classification_map": {
                        "entities/concept/**": "public",
                        "entities/concept/x.json": "restricted",
                    }}
        self.assertEqual(
            ce.classify_entity({"id": "concept:x", "kind": "concept"}, manifest),
            "restricted")

    def test_no_matching_glob_falls_through_to_corpus_level(self):
        manifest = {"data_classification": "internal",
                    "classification_map": {"entities/person/**": "restricted"}}
        self.assertEqual(
            ce.classify_entity({"id": "org:x", "kind": "org"}, manifest),
            "internal")


class TestClassificationCapEnv(unittest.TestCase):
    """_classification_cap() reads CB_CLASSIFICATION_CAP ONLY."""

    def setUp(self):
        self._prev = os.environ.get("CB_CLASSIFICATION_CAP")

    def tearDown(self):
        if self._prev is None:
            os.environ.pop("CB_CLASSIFICATION_CAP", None)
        else:
            os.environ["CB_CLASSIFICATION_CAP"] = self._prev

    def test_unset_defaults_to_restricted_full_read(self):
        os.environ.pop("CB_CLASSIFICATION_CAP", None)
        self.assertEqual(ce._classification_cap(), "restricted")

    def test_recognized_value_passes_through(self):
        os.environ["CB_CLASSIFICATION_CAP"] = "internal"
        self.assertEqual(ce._classification_cap(), "internal")

    def test_case_and_whitespace_insensitive(self):
        os.environ["CB_CLASSIFICATION_CAP"] = "  Confidential  "
        self.assertEqual(ce._classification_cap(), "confidential")

    def test_garbage_value_fails_closed_to_public(self):
        os.environ["CB_CLASSIFICATION_CAP"] = "not-a-real-level"
        self.assertEqual(ce._classification_cap(), "public")


class TestRequestCapContextVar(unittest.TestCase):
    """M12 seam: request_cap() ContextVar override on top of the M7 env gate.

    Unit-level isolation only — necessary but NOT sufficient for the real
    propagation risk. A threadpool-dispatching FastMCP server could pass
    every test in this class and still leak one caller's cap into another
    concurrent request at dispatch time if middleware wires request_cap()
    incorrectly; that end-to-end middleware->contextvar->handler proof
    belongs to the served-mode task's transport tests, not here.
    """

    def setUp(self):
        self._prev = os.environ.get("CB_CLASSIFICATION_CAP")

    def tearDown(self):
        if self._prev is None:
            os.environ.pop("CB_CLASSIFICATION_CAP", None)
        else:
            os.environ["CB_CLASSIFICATION_CAP"] = self._prev

    def test_override_beats_env(self):
        os.environ["CB_CLASSIFICATION_CAP"] = "restricted"
        with ce.request_cap("public"):
            self.assertEqual(ce._classification_cap(), "public")

    def test_reset_restores_env_backed_value_on_exit(self):
        os.environ["CB_CLASSIFICATION_CAP"] = "internal"
        with ce.request_cap("restricted"):
            self.assertEqual(ce._classification_cap(), "restricted")
        self.assertEqual(ce._classification_cap(), "internal")

    def test_reset_restores_unset_env_on_exit(self):
        os.environ.pop("CB_CLASSIFICATION_CAP", None)
        with ce.request_cap("confidential"):
            self.assertEqual(ce._classification_cap(), "confidential")
        self.assertEqual(ce._classification_cap(), "restricted")

    def test_unset_override_falls_through_to_env_byte_identical(self):
        # No `with request_cap(...)` active anywhere -> identical to pre-M12
        # env-only behavior, for both the "unset env" and "set env" cases.
        os.environ.pop("CB_CLASSIFICATION_CAP", None)
        self.assertEqual(ce._classification_cap(), "restricted")
        os.environ["CB_CLASSIFICATION_CAP"] = "public"
        self.assertEqual(ce._classification_cap(), "public")

    def test_unrecognized_override_fails_closed_to_public_like_env(self):
        os.environ.pop("CB_CLASSIFICATION_CAP", None)
        with ce.request_cap("not-a-real-level"):
            self.assertEqual(ce._classification_cap(), "public")

    def test_nested_overrides_restore_the_outer_value(self):
        with ce.request_cap("internal"):
            with ce.request_cap("public"):
                self.assertEqual(ce._classification_cap(), "public")
            self.assertEqual(ce._classification_cap(), "internal")

    def test_override_isolated_per_thread(self):
        os.environ.pop("CB_CLASSIFICATION_CAP", None)
        results: dict[str, str] = {}
        barrier = threading.Barrier(2, timeout=5)

        def worker(level: str, key: str) -> None:
            with ce.request_cap(level):
                barrier.wait()  # force both threads to hold their override concurrently
                results[key] = ce._classification_cap()

        t1 = threading.Thread(target=worker, args=("public", "t1"))
        t2 = threading.Thread(target=worker, args=("confidential", "t2"))
        t1.start()
        t2.start()
        t1.join()
        t2.join()

        self.assertEqual(results["t1"], "public")
        self.assertEqual(results["t2"], "confidential")
        # Main thread's context was never touched by either worker thread.
        self.assertEqual(ce._classification_cap(), "restricted")

    def test_override_isolated_per_asyncio_task(self):
        os.environ.pop("CB_CLASSIFICATION_CAP", None)

        async def worker(level: str) -> str:
            with ce.request_cap(level):
                await asyncio.sleep(0)  # yield control while override is held
                return ce._classification_cap()

        async def main() -> tuple[str, str, str]:
            t1 = asyncio.create_task(worker("public"))
            t2 = asyncio.create_task(worker("internal"))
            r1, r2 = await asyncio.gather(t1, t2)
            return r1, r2, ce._classification_cap()

        cap1, cap2, cap_after = asyncio.run(main())
        self.assertEqual(cap1, "public")
        self.assertEqual(cap2, "internal")
        self.assertEqual(cap_after, "restricted")


class TestClassificationGateEndToEnd(unittest.TestCase):
    """Drives every read endpoint against the mixed-classification fixture."""

    @classmethod
    def setUpClass(cls):
        _ensure_corpus_built()
        cls.corpus_dir = CORPUS

    def setUp(self):
        self._prev = os.environ.get("CB_CLASSIFICATION_CAP")

    def tearDown(self):
        if self._prev is None:
            os.environ.pop("CB_CLASSIFICATION_CAP", None)
        else:
            os.environ["CB_CLASSIFICATION_CAP"] = self._prev

    def _set_cap(self, cap: str | None) -> None:
        if cap is None:
            os.environ.pop("CB_CLASSIFICATION_CAP", None)
        else:
            os.environ["CB_CLASSIFICATION_CAP"] = cap

    def test_filter_by_classification_counts_per_cap(self):
        entities = ce.load_corpus(self.corpus_dir)
        self.assertEqual(len(entities), TOTAL)

        cases = [
            # cap -> expected withheld_count
            ("public", TOTAL - len(CONCEPT_IDS)),
            ("internal", TOTAL - len(CONCEPT_IDS) - len(ORG_IDS)),
            ("confidential", len(PERSON_IDS)),
            ("restricted", 0),
        ]
        for cap, expected_withheld in cases:
            with self.subTest(cap=cap):
                self._set_cap(cap)
                kept, withheld, effective_cap = ce._filter_by_classification(
                    entities, self.corpus_dir)
                self.assertEqual(effective_cap, cap)
                self.assertEqual(withheld, expected_withheld)
                self.assertEqual(len(kept), TOTAL - expected_withheld)
                # confidential override never appears below its own rank
                if cap in ("public", "internal"):
                    self.assertNotIn(CONFIDENTIAL_OVERRIDE_ID, kept)
                else:
                    self.assertIn(CONFIDENTIAL_OVERRIDE_ID, kept)
                # persons never appear below 'restricted'
                if cap != "restricted":
                    self.assertFalse(PERSON_IDS & set(kept))
                else:
                    self.assertTrue(PERSON_IDS <= set(kept))

    def test_stats_reports_transparency_block(self):
        self._set_cap("public")
        s = ce.stats(corpus_dir=str(self.corpus_dir))
        self.assertEqual(s["effective_cap"], "public")
        self.assertEqual(s["withheld_count"], TOTAL - len(CONCEPT_IDS))
        self.assertEqual(s["entity_count"], len(CONCEPT_IDS))

    def test_resolve_never_returns_a_capped_entity(self):
        self._set_cap("public")
        r = ce.resolve("Elena Vasko", corpus_dir=str(self.corpus_dir))
        self.assertEqual(r["matches"], [])
        self.assertGreater(r["withheld_count"], 0)
        self.assertEqual(r["effective_cap"], "public")

        self._set_cap("restricted")
        r2 = ce.resolve("Elena Vasko", corpus_dir=str(self.corpus_dir))
        self.assertTrue(any(m["id"] == "person:elena-vasko" for m in r2["matches"]))

    def test_wiki_ask_withholds_neighbors_above_cap(self):
        # A public concept links to org:atlas-marine (classified 'internal').
        self._set_cap("public")
        a = ce.wiki_ask("Atlas Marine Stability-Aware Routing Demand",
                        corpus_dir=str(self.corpus_dir), depth=1, budget=8000,
                        mode="substring")
        matched_ids = [m["id"] for m in a["matched"]]
        neighbor_ids = [n["id"] for n in a["neighbors"]]
        self.assertIn("concept:atlas-marine-demand-theme", matched_ids)
        self.assertNotIn("org:atlas-marine", neighbor_ids,
                         "org classified above the 'public' cap leaked as a neighbor")
        self.assertGreater(a["stats"]["withheld_count"], 0)
        self.assertEqual(a["stats"]["effective_cap"], "public")

        # Raise the cap to 'internal' — the org neighbor should now surface.
        self._set_cap("internal")
        a2 = ce.wiki_ask("Atlas Marine Stability-Aware Routing Demand",
                         corpus_dir=str(self.corpus_dir), depth=1, budget=8000,
                         mode="substring")
        neighbor_ids2 = [n["id"] for n in a2["neighbors"]]
        self.assertIn("org:atlas-marine", neighbor_ids2)

    def test_wiki_ask_confidential_entity_needs_confidential_cap(self):
        self._set_cap("internal")
        a = ce.wiki_ask("Atlas Marine Named As Routing Partner",
                        corpus_dir=str(self.corpus_dir), depth=0, budget=8000,
                        mode="substring")
        self.assertNotIn(CONFIDENTIAL_OVERRIDE_ID, [m["id"] for m in a["matched"]])

        self._set_cap("confidential")
        a2 = ce.wiki_ask("Atlas Marine Named As Routing Partner",
                         corpus_dir=str(self.corpus_dir), depth=0, budget=8000,
                         mode="substring")
        self.assertIn(CONFIDENTIAL_OVERRIDE_ID, [m["id"] for m in a2["matched"]])

    def test_wiki_pack_reports_transparency_block_and_withholds(self):
        self._set_cap("public")
        pack = ce.wiki_pack("Atlas Marine Stability-Aware Routing Demand",
                            corpus_dir=str(self.corpus_dir), budget=4000, mode="substring")
        item_ids = [it["id"] for it in pack["items"]]
        self.assertNotIn("org:atlas-marine", item_ids)
        self.assertEqual(pack["stats"]["effective_cap"], "public")
        self.assertGreater(pack["stats"]["withheld_count"], 0)

    def test_wiki_audit_scopes_the_whole_audit_to_the_cap(self):
        self._set_cap("internal")
        audit = ce.wiki_audit(corpus_dir=str(self.corpus_dir))
        self.assertEqual(audit["effective_cap"], "internal")
        self.assertEqual(audit["withheld_count"], len(PERSON_IDS) + 1)  # persons + confidential
        self.assertEqual(audit["entity_count_audited"],
                         TOTAL - len(PERSON_IDS) - 1)
        # orphans/dead_links must never reference a withheld entity's content —
        # they may reference the id (that's the point of dead_links), but no
        # withheld id should appear in an *orphans* listing.
        orphan_ids = {o["id"] for o in audit["orphans"]}
        self.assertFalse(PERSON_IDS & orphan_ids)

    def test_unset_cap_is_full_backward_compatible_read(self):
        self._set_cap(None)
        s = ce.stats(corpus_dir=str(self.corpus_dir))
        self.assertEqual(s["effective_cap"], "restricted")
        self.assertEqual(s["withheld_count"], 0)
        self.assertEqual(s["entity_count"], TOTAL)


if __name__ == "__main__":
    unittest.main()
