#!/usr/bin/env python3
"""Golden-query retrieval gate for wiki_ask / wiki_pack.

wiki_pack's depth-banded packing was proven at exactly one data point before
this suite existed (3997/4000 tokens, see cb_engine.py history) and wiki_ask
had zero retrieval-quality coverage. This suite pins ~40 queries against a
frozen SYNTHETIC fixture (entitystore/scripts/tests/fixtures/golden_corpus/,
generated by fixtures/build_golden_corpus.py from fixtures/golden_seed.json)
so future changes to scoring, neighbor expansion, or depth-banding in
cb_engine.py are falsifiable instead of unfalsifiable.

Default run is fully hermetic: mode=substring only, no network calls, no
embedding provider, no real company-brain data (this repo, VictorGjn/
agent-skills, is PUBLIC — see fixtures/README.md for the data-governance
rationale). A second, opt-in, env-gated test class
(TestGoldenQueriesAgainstLiveCorpus) runs a relaxed recall-only subset of the
same query IDs against a REAL local company-brain corpus, only when
CB_GOLDEN_LIVE_CORPUS is set — see fixtures/README.md for how to run it. That
class touches real data, is never part of default CI, and never writes
anything back to the fixture.

Run: python -m pytest entitystore/scripts/tests/test_golden_queries.py -v
     (or) python entitystore/scripts/tests/test_golden_queries.py
"""
from __future__ import annotations

import json
import os
import pathlib
import sys
import unittest

SCRIPTS = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

import cb_engine as ce  # noqa: E402

FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"
SYNTHETIC_CORPUS = FIXTURES / "golden_corpus"
QUERIES_PATH = FIXTURES / "golden_queries.json"


def _load_cases() -> list[dict]:
    data = json.loads(QUERIES_PATH.read_text(encoding="utf-8"))
    return data["cases"]


def _ensure_synthetic_corpus_built() -> None:
    """Regenerate the fixture on the fly if it's missing (e.g. fresh checkout
    before anyone has run build_golden_corpus.py). Cheap and deterministic."""
    if (SYNTHETIC_CORPUS / "entities").exists():
        return
    sys.path.insert(0, str(FIXTURES))
    import build_golden_corpus  # noqa: E402 (import-after-sys.path-insert intentional)
    build_golden_corpus.build(write=True)


def _run_ask(case: dict, corpus_dir: pathlib.Path) -> dict:
    params = dict(case["params"])
    return ce.wiki_ask(case["query"], corpus_dir=str(corpus_dir), **params)


def _run_pack(case: dict, corpus_dir: pathlib.Path) -> dict:
    params = dict(case["params"])
    return ce.wiki_pack(case["query"], corpus_dir=str(corpus_dir), **params)


class TestGoldenQueriesSynthetic(unittest.TestCase):
    """Default, hermetic gate — runs in CI on every PR (once activated, see
    fixtures/README.md "Manual go-live step"). Never touches real data."""

    @classmethod
    def setUpClass(cls):
        _ensure_synthetic_corpus_built()
        cls.corpus_dir = SYNTHETIC_CORPUS
        cls.cases = _load_cases()

    def test_all_cases_present_and_well_formed(self):
        self.assertGreaterEqual(len(self.cases), 30,
                                 "golden_queries.json should carry >=30 cases")
        self.assertLessEqual(len(self.cases), 50,
                              "golden_queries.json should carry <=50 cases")
        ids = [c["id"] for c in self.cases]
        self.assertEqual(len(ids), len(set(ids)), "duplicate case ids")
        author = sum(1 for c in self.cases if c["truth"] == "author")
        self.assertGreaterEqual(author / len(self.cases), 0.5,
                                 "at least half the cases should be author-ground-truth")

    def test_fixture_schema_validates(self):
        """Validate that the golden corpus conforms to the vendored schema.
        This catches schema drift (e.g. fixtures gaining fields without schema update)."""
        sys.path.insert(0, str(FIXTURES))
        import build_golden_corpus  # noqa: E402
        # Regenerate corpus to ensure seed is up-to-date, then validate.
        entities = build_golden_corpus.build(write=False)
        errors = build_golden_corpus.validate(entities)
        self.assertEqual(errors, [],
                         f"fixture schema validation failed: {errors}")

    def test_wiki_ask_cases(self):
        for case in self.cases:
            if case["endpoint"] != "wiki_ask":
                continue
            with self.subTest(case=case["id"]):
                result = _run_ask(case, self.corpus_dir)
                expect = case["expect"]
                matched_ids = [m["id"] for m in result["matched"]]
                neighbor_ids = [n["id"] for n in result["neighbors"]]

                if "top_id" in expect:
                    top = matched_ids[0] if matched_ids else None
                    self.assertEqual(top, expect["top_id"],
                                      f"{case['id']}: top_id mismatch, matched={matched_ids}")
                if "matched_set" in expect:
                    self.assertEqual(set(matched_ids), set(expect["matched_set"]),
                                      f"{case['id']}: matched set mismatch")
                if "min_matched" in expect:
                    self.assertGreaterEqual(len(matched_ids), expect["min_matched"],
                                             f"{case['id']}: too few matched")
                if "neighbors_set" in expect:
                    self.assertEqual(set(neighbor_ids), set(expect["neighbors_set"]),
                                      f"{case['id']}: neighbor set mismatch")
                if "neighbors_superset" in expect:
                    missing = set(expect["neighbors_superset"]) - set(neighbor_ids)
                    self.assertFalse(missing, f"{case['id']}: missing neighbors {missing}")
                if "min_neighbors" in expect:
                    self.assertGreaterEqual(len(neighbor_ids), expect["min_neighbors"],
                                             f"{case['id']}: too few neighbors")
                if "absent_ids" in expect:
                    present = (set(matched_ids) | set(neighbor_ids)) & set(expect["absent_ids"])
                    self.assertFalse(present, f"{case['id']}: unexpected ids present {present}")
                if "error_contains" in expect:
                    self.assertIn(expect["error_contains"], result["stats"].get("error", ""),
                                  f"{case['id']}: expected error substring not found")
                if "min_dropped_by_freshness" in expect:
                    dropped = result["stats"].get("dropped_by_freshness", 0)
                    self.assertGreaterEqual(dropped, expect["min_dropped_by_freshness"],
                                             f"{case['id']}: too few entities dropped by freshness")

    def test_wiki_pack_cases(self):
        for case in self.cases:
            if case["endpoint"] != "wiki_pack":
                continue
            with self.subTest(case=case["id"]):
                result = _run_pack(case, self.corpus_dir)
                expect = case["expect"]
                item_ids = [it["id"] for it in result["items"]]
                depth_by_id = {it["id"]: it["depth"] for it in result["items"]}
                budget = case["params"]["budget"]

                # used_tokens must always respect the budget (or be the
                # unconstrained single-item floor — never balloon past it).
                self.assertLessEqual(result["used_tokens"], expect.get("max_used_tokens", budget),
                                      f"{case['id']}: used_tokens exceeded budget")

                if "item_count" in expect:
                    self.assertEqual(len(item_ids), expect["item_count"],
                                      f"{case['id']}: item count mismatch, got {item_ids}")
                if "present_ids" in expect:
                    missing = set(expect["present_ids"]) - set(item_ids)
                    self.assertFalse(missing, f"{case['id']}: missing items {missing}")
                if "depth_exactly" in expect:
                    for eid, want_depth in expect["depth_exactly"].items():
                        self.assertIn(eid, depth_by_id, f"{case['id']}: {eid} not in pack")
                        self.assertEqual(depth_by_id[eid], want_depth,
                                          f"{case['id']}: {eid} depth mismatch")
                if "min_distinct_depth_names" in expect:
                    distinct = {it["depth_name"] for it in result["items"]}
                    self.assertGreaterEqual(len(distinct), expect["min_distinct_depth_names"],
                                             f"{case['id']}: depth band spread too narrow "
                                             f"({distinct}) — demotion not exercised")


@unittest.skipUnless(os.environ.get("CB_GOLDEN_LIVE_CORPUS"),
                      "opt-in only — set CB_GOLDEN_LIVE_CORPUS=1 and CB_CORPUS_DIR to a "
                      "local, already-private company-brain checkout to run this sanity check")
class TestGoldenQueriesAgainstLiveCorpus(unittest.TestCase):
    """Opt-in, local-only sanity check: do the synthetic fixture's assertions
    stay directionally sane against the REAL live corpus? This is the ONLY
    code path in this suite that may see real entities. It is never part of
    default CI (this repo is public), never runs unless explicitly enabled,
    and never writes anything back to the fixture or commits real data
    anywhere. Assertions here are deliberately relaxed (recall-only, no
    exact-id/depth pinning) since the real corpus's content and size are
    outside this suite's control.
    """

    @classmethod
    def setUpClass(cls):
        corpus_env = os.environ.get("CB_CORPUS_DIR")
        if not corpus_env:
            raise unittest.SkipTest("CB_GOLDEN_LIVE_CORPUS set but CB_CORPUS_DIR is not")
        cls.corpus_dir = pathlib.Path(corpus_env)

    def test_wiki_ask_returns_results_for_broad_queries(self):
        # Recall-only: confirm the engine returns *something* sane against
        # real data, not that it returns our synthetic ids.
        for query in ("routing", "stability", "partnership"):
            with self.subTest(query=query):
                result = ce.wiki_ask(query, corpus_dir=str(self.corpus_dir),
                                      mode="substring", depth=1, top=10)
                self.assertIsInstance(result["matched"], list)
                self.assertIn("stats", result)

    def test_wiki_pack_respects_budget_on_real_corpus(self):
        for budget in (1200, 300):
            with self.subTest(budget=budget):
                result = ce.wiki_pack("routing", corpus_dir=str(self.corpus_dir),
                                       mode="substring", budget=budget)
                self.assertLessEqual(result["used_tokens"], budget)


if __name__ == "__main__":
    unittest.main()
